import { mapContextModalStep, modalStep } from "@/lib/onboarding/tourStepHelpers";
import type { TourChapter } from "@/lib/onboarding/chapters/types";

export const ADMIN_CHAPTERS: TourChapter[] = [
  {
    id: "essentials",
    title: "Primeiros passos",
    description: "Sininho, menus, mapa, pin de exemplo, agendar visita e sincronizar.",
    steps: [
      modalStep(
        "Bem-vindo ao painel",
        "Capítulo essencial: avisos, mapa com sede, pin fictício NSI-GUIA-001 e agendamento simulado. Outros capítulos no ? cobrem filtros, rotas e agenda."
      ),
      {
        element: '[data-tour="admin-views"]',
        title: "Onde trabalha",
        description:
          "Mapa, calendário ou histórico — muda com estes botões no computador (no telemóvel, o mesmo está no menu ☰).",
        side: "bottom",
        viewport: "desktop",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["closeAdminMobileMenu", "closeAdminDesktopMenu"],
      },
      {
        element: '[data-tour="admin-header-notifications"]',
        title: "Sininho — avisos da agenda",
        description:
          "Visitas agendadas, reagendadas, em curso, concluídas, incompletas, canceladas ou removidas. Abrir o sininho marca tudo como lido; toque num aviso para «Ver serviço».",
        side: "bottom",
        fallbackModalIfMissing: true,
      },
      {
        element: '[data-tour="admin-mobile-menu-trigger"]',
        title: "Menu no telemóvel (☰)",
        description:
          "Vistas, pesquisa, sincronizar, guia ? e conta. Abrimos o menu nos passos seguintes.",
        side: "bottom",
        viewport: "mobile",
        fallbackModalIfMissing: true,
      },
      {
        element: '[data-tour="admin-mobile-menu-sheet"]',
        title: "Menu móvel",
        description:
          "Vistas em cima, depois Pesquisar e Sincronizar CRM, guia ? e Tema / Sair.",
        side: "top",
        viewport: "mobile",
        fallbackModalIfMissing: true,
        prepareOnHighlight: "openAdminMobileMenu",
      },
      {
        element: '[data-tour="admin-nav-map"]',
        title: "Vamos ao mapa",
        description: "Sede, técnicos, clientes e o pin de formação.",
        side: "bottom",
        tourAction: "showAdminViewMap",
        prepareOnHighlight: [
          "closeAdminDesktopMenu",
          "showAdminViewMap",
          "openAdminMobileMenu",
        ],
        fallbackModalIfMissing: true,
      },
      {
        element: '[data-tour="admin-map-canvas"]',
        focusDemoPin: true,
        title: "Pin de formação",
        description:
          "Pin verde «Instalação» fictício (NSI-GUIA-001), por agendar. Toque «Abrir painel» ou avance.",
        align: "center",
        side: "bottom",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "setAdminMapTabUnscheduled"],
      },
      {
        element: '[data-tour="admin-demo-open-opportunity"]',
        title: "Abrir oportunidade de exemplo",
        description: "Abrimos o painel lateral de formação no passo seguinte.",
        side: "top",
        fallbackModalIfMissing: true,
        focusDemoPin: true,
        prepareOnHighlight: ["showAdminViewMap", "setAdminMapTabUnscheduled"],
      },
      {
        element: '[data-tour="admin-opp-drawer"]',
        title: "Painel da oportunidade",
        description: "Cliente, notas, GPS e agendamento — deslize para ver tudo.",
        side: "bottom",
        align: "center",
        tourAction: "openAdminDemoOpportunity",
        drawerStep: true,
      },
      {
        element: '[data-tour="admin-opp-schedule-btn"]',
        title: "Agendar visita",
        description: "Ícone de calendário — abre o formulário enquanto não houver visita marcada.",
        side: "left",
        drawerStep: true,
        prepareOnHighlight: "openAdminDemoOpportunity",
      },
      {
        element: '[data-tour="admin-schedule-submit"]',
        title: "Confirmar agendamento",
        description:
          "Escolha data, hora e técnico válido. No guia simula o envio; no trabalho real grava no Twenty.",
        side: "top",
        sheetStep: true,
        prepareOnHighlight: ["openAdminDemoScheduleModal", "seedAdminDemoScheduleForm"],
      },
      {
        element: '[data-tour="admin-search"]',
        title: "Pesquisa (Ctrl+K)",
        description:
          "NSI, cliente, morada ou técnico. Enter com vários resultados filtra o mapa.",
        side: "bottom",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "openAdminMobileMenu"],
      },
      {
        element: '[data-tour="admin-refresh"]',
        title: "Sincronizar CRM",
        description:
          "Recalcula moradas/GPS no Twenty e recarrega os serviços. Mostra a hora da última sync no computador.",
        side: "left",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "openAdminMobileMenu"],
      },
      {
        element: '[data-tour="tour-help-button"]',
        title: "Capítulos do guia",
        description: "O ? lista capítulos — filtros, rotas, cancelamentos, agenda.",
        side: "bottom",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "openAdminMobileMenu", "closeAdminDesktopMenu"],
      },
    ],
  },
  {
    id: "map-filters",
    title: "Mapa e filtros",
    description: "Sede, técnicos em campo, painel Filtros, Zonas e controlos do mapa.",
    steps: [
      modalStep(
        "Mapa operacional",
        "Sede, carrinhas, filtros avançados e legenda — tudo simulação onde indicado."
      ),
      {
        element: '[data-tour="admin-nav-map"]',
        title: "Mapa",
        tourAction: "showAdminViewMap",
        description: "Centro do planeamento diário.",
        side: "bottom",
        prepareOnHighlight: [
          "showAdminViewMap",
          "stopAdminDemoTechnicianAnimation",
          "openAdminMobileMenu",
        ],
        fallbackModalIfMissing: true,
      },
      mapContextModalStep(
        "Sede da empresa",
        "O logótipo marca a sede — ponto de partida e regresso das rotas otimizadas.",
        ["showAdminViewMap", "stopAdminDemoTechnicianAnimation", "openAdminMapHqPanel"]
      ),
      mapContextModalStep(
        "Carrinha do técnico (exemplo)",
        "Ícone verde-lima no mapa — toque para ver nome e visitas de hoje. Simulação junto ao pin verde do cliente.",
        ["showAdminViewMap", "stopAdminDemoTechnicianAnimation", "selectAdminDemoTechnician"]
      ),
      mapContextModalStep(
        "Deslocação simulada",
        "A carrinha «João — exemplo do guia» move-se em direção ao NSI-GUIA-001. No trabalho real, o GPS do técnico actualiza a posição.",
        ["showAdminViewMap", "selectAdminDemoTechnician", "animateAdminDemoTechnician"]
      ),
      {
        element: '[data-tour="admin-map-filters"]',
        title: "Abrir filtros",
        description: "Toque «Filtros» — número verde = filtros activos; cinzento = pins visíveis.",
        side: "bottom",
        fallbackModalIfMissing: true,
        prepareOnHighlight: [
          "showAdminViewMap",
          "stopAdminDemoTechnicianAnimation",
          "setAdminMapTabUnscheduled",
          "openAdminMapFiltersPanel",
        ],
      },
      {
        element: '[data-tour="admin-map-status-tabs"]',
        title: "Estado no mapa",
        description: "Todos / Por agendar / Agendados — separado do histórico (Concluído, Incompleto, Cancelado).",
        side: "bottom",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "openAdminMapFiltersPanel"],
      },
      {
        element: '[data-tour="admin-map-zones-button"]',
        title: "Botão Zonas",
        description: "Assistente em 3 passos: método → zona → acção (rota automática ou seleção manual).",
        side: "bottom",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "closeAdminMapFiltersPanel"],
      },
      {
        element: '[data-tour="admin-map-zones-panel"]',
        title: "Assistente de zonas",
        description: "Analise zonas geográficas antes de planear rotas ou agendar em massa.",
        side: "bottom",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "openAdminMapZonesPanel"],
      },
      {
        element: '[data-tour="admin-map-controls"]',
        title: "Controlos do mapa",
        description: "Ajustar aos pinos, centrar na sede, agrupar pinos e legenda de cores.",
        side: "left",
        prepareOnHighlight: ["showAdminViewMap", "closeAdminMapZonesPanel", "closeAdminMapFiltersPanel"],
        fallbackModalIfMissing: true,
      },
    ],
  },
  {
    id: "schedule-cancel",
    title: "Agendar e cancelar",
    description: "Formulário completo, visita urgente, morada, notas e cancelamento.",
    steps: [
      modalStep(
        "Agendamento",
        "Formulário completo na oportunidade fictícia; depois mostramos cancelamento num exemplo agendado."
      ),
      {
        element: '[data-tour="admin-opp-drawer"]',
        title: "Oportunidade de exemplo",
        tourAction: "openAdminDemoOpportunity",
        description: "Serviço por agendar — NSI-GUIA-001.",
        side: "bottom",
        align: "center",
        drawerStep: true,
      },
      {
        element: '[data-tour="admin-opp-notes"]',
        title: "Notas do CRM",
        description: "Instruções comerciais antes de marcar visita.",
        side: "bottom",
        drawerStep: true,
      },
      {
        element: '[data-tour="admin-opp-client-block"]',
        title: "Contactos",
        description: "Telefones e e-mail — confirme antes de agendar.",
        side: "bottom",
        drawerStep: true,
      },
      {
        element: '[data-tour="admin-opp-gps-btn"]',
        title: "Atualizar GPS",
        description: "Recalcula coordenadas a partir da morada. No guia é simulação.",
        side: "bottom",
        drawerStep: true,
        prepareOnHighlight: "openAdminDemoOpportunity",
      },
      {
        element: '[data-tour="admin-schedule-modal"]',
        title: "Formulário de agendamento",
        description: "Simulação — altere campos à vontade.",
        side: "bottom",
        align: "center",
        sheetStep: true,
        prepareOnHighlight: "openAdminDemoScheduleModal",
      },
      {
        element: '[data-tour="admin-schedule-title-datetime"]',
        title: "Título, data e hora",
        description: "Data não no passado; aviso se hora fora do horário habitual.",
        side: "right",
        sheetStep: true,
        prepareOnHighlight: ["openAdminDemoScheduleModal", "seedAdminDemoScheduleForm"],
      },
      {
        element: '[data-tour="admin-schedule-technician"]',
        title: "Escolher técnico",
        description:
          "Obrigatório. Sem técnico o botão fica desactivado; contas inválidas são recusadas ao gravar.",
        side: "right",
        sheetStep: true,
      },
      {
        element: '[data-tour="admin-schedule-urgent"]',
        title: "Visita urgente",
        description: "Permite sobrepor outra visita do mesmo técnico — confirmação extra.",
        side: "top",
        sheetStep: true,
      },
      {
        element: '[data-tour="admin-schedule-address"]',
        title: "Morada",
        description: "Rua, cidade e código postal para o técnico e GPS.",
        side: "left",
        sheetStep: true,
      },
      {
        element: '[data-tour="admin-schedule-notes"]',
        title: "Instruções",
        description: "Acesso, portão, estacionamento — visíveis na visita do técnico.",
        side: "left",
        sheetStep: true,
      },
      {
        element: '[data-tour="admin-schedule-submit"]',
        title: "Agendar visita",
        description: "Revise e confirme. Toast de formação no guia.",
        side: "top",
        sheetStep: true,
      },
      {
        element: '[data-tour="admin-opp-in-progress-banner"]',
        title: "Visita em curso",
        description: "Banner quando o técnico marcou «Cheguei ao local» — exemplo simulado.",
        side: "bottom",
        drawerStep: true,
        tourAction: "setAdminDemoOpportunityInProgress",
        prepareOnHighlight: "setAdminDemoOpportunityInProgress",
      },
      {
        element: '[data-tour="admin-opp-cancel-btn"]',
        title: "Cancelar agendamento",
        description: "Remove a visita agendada e volta o serviço a «por agendar». Simulação no guia.",
        side: "left",
        drawerStep: true,
        tourAction: "setAdminDemoOpportunityScheduled",
        prepareOnHighlight: "setAdminDemoOpportunityScheduled",
      },
    ],
  },
  {
    id: "routes-mass",
    title: "Rotas e agendamento em massa",
    description: "Selecção manual, roteiro optimizado e modal de agendamento em massa.",
    steps: [
      modalStep(
        "Rotas",
        "Seleccione paragens no mapa, optimice e agende várias visitas de uma vez — dados fictícios."
      ),
      {
        element: '[data-tour="admin-nav-map"]',
        title: "Mapa",
        description: "Comece sempre no mapa para seleccionar paragens.",
        side: "bottom",
        tourAction: "showAdminViewMap",
        prepareOnHighlight: [
          "showAdminViewMap",
          "startAdminDemoRouteSelection",
          "openAdminMobileMenu",
        ],
        fallbackModalIfMissing: true,
      },
      {
        element: '[data-tour="admin-route-mode-banner"]',
        title: "Modo de selecção",
        description: "Escolha pins no mapa — «Na rota / Remover» no popup de cada serviço.",
        side: "bottom",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "startAdminDemoRouteSelection"],
      },
      {
        element: '[data-tour="admin-route-sidebar"]',
        title: "Painel de roteiro",
        description: "Passos Selecionar → Otimizar → Agendar; reordene paragens e veja custos.",
        side: "left",
        viewport: "desktop",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "startAdminDemoRouteSelection"],
      },
      {
        element: '[data-tour="admin-route-open-sheet"]',
        title: "Ver roteiro (mobile)",
        description: "No telemóvel, abra o roteiro num painel inferior.",
        side: "top",
        viewport: "mobile",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "startAdminDemoRouteSelection", "openAdminDemoRouteSheet"],
      },
      {
        element: '[data-tour="admin-route-actions"]',
        title: "Optimizar e agendar",
        description: "Calcule paragens, estime combustível e abra agendamento em massa.",
        side: "top",
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["showAdminViewMap", "startAdminDemoRouteSelection"],
      },
      {
        element: '[data-tour="admin-mass-schedule-modal"]',
        title: "Agendamento em massa",
        description: "Técnico, data, notas da rota e horário por paragem — simulação no guia.",
        side: "bottom",
        align: "center",
        sheetStep: true,
        tourAction: "openAdminDemoMassSchedule",
        prepareOnHighlight: "openAdminDemoMassSchedule",
      },
    ],
  },
  {
    id: "calendar-history",
    title: "Agenda e histórico",
    description: "Calendário partilhado, filtro por técnico e histórico com relatório.",
    steps: [
      modalStep(
        "Agenda e histórico",
        "Planear visitas agendadas e consultar intervenções passadas."
      ),
      {
        element: '[data-tour="admin-nav-calendar"]',
        title: "Vista Agenda",
        description: "Calendário partilhado das visitas agendadas; filtre por técnico.",
        side: "bottom",
        tourAction: "showAdminViewCalendar",
        prepareOnHighlight: ["showAdminViewCalendar", "openAdminMobileMenu"],
      },
      {
        element: '[data-tour="admin-calendar-rbc-toolbar"]',
        title: "Navegação do calendário",
        description: "Hoje, anterior/próximo e Mês / Semana / Dia / Agenda.",
        side: "bottom",
        fallbackModalIfMissing: true,
        prepareOnHighlight: "showAdminViewCalendar",
      },
      {
        element: '[data-tour="admin-calendar-tech-filter"]',
        title: "Filtrar por técnico",
        description: "Reduza o calendário a um técnico.",
        side: "bottom",
        prepareOnHighlight: "showAdminViewCalendar",
        fallbackModalIfMissing: true,
      },
      {
        element: '[data-tour="admin-calendar-list-btn"]',
        title: "Lista Agenda (mobile)",
        description: "Toque para ver a lista de visitas do dia num painel.",
        side: "bottom",
        viewport: "mobile",
        fallbackModalIfMissing: true,
        prepareOnHighlight: "showAdminViewCalendar",
      },
      {
        element: '[data-tour="admin-nav-history"]',
        title: "Vista Histórico",
        description: "Concluídas, incompletas ou canceladas.",
        side: "bottom",
        tourAction: "showAdminViewHistory",
        prepareOnHighlight: ["showAdminViewHistory", "openAdminMobileMenu"],
      },
      {
        element: '[data-tour="admin-history"]',
        title: "Histórico",
        description: "Resumo por estado e lista paginada.",
        side: "bottom",
        prepareOnHighlight: "showAdminViewHistory",
        fallbackModalIfMissing: true,
      },
      {
        element: '[data-tour="admin-opp-report"]',
        title: "Relatório do técnico",
        description: "No painel lateral de um registo histórico — leia o que foi feito em campo.",
        side: "bottom",
        drawerStep: true,
        fallbackModalIfMissing: true,
        tourAction: "openAdminDemoHistoryOpportunity",
        prepareOnHighlight: "openAdminDemoHistoryOpportunity",
      },
      {
        element: '[data-tour="admin-menu-ceo"]',
        title: "Painel CEO",
        description: "Métricas executivas — disponível para admin e CEO.",
        side: "left",
        roles: ["admin", "ceo"],
        fallbackModalIfMissing: true,
        prepareOnHighlight: ["openAdminDesktopMenu", "openAdminMobileMenu"],
      },
      {
        element: '[data-tour="admin-menu-sre"]',
        title: "Consola SRE",
        description: "Observabilidade e testes E2E — só administradores Twenty.",
        side: "left",
        roles: ["admin"],
        fallbackModalIfMissing: true,
        prepareOnHighlight: "openAdminDesktopMenu",
      },
    ],
  },
];
